<a href="https://colab.research.google.com/github/mukulSharma6230/mukul/blob/main/Data_Preprocessing_Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a= np.zeros(5)
print(a)
print(a[2:5])

[0. 0. 0. 0. 0.]
[0. 0. 0.]


in this  if write : this sign in between them it will shows only rows and if we write the , between 2 then it will print the thing we want

In [9]:
list1 =np.array([[1,2,3],[4,5,6],[7,8,9]])
print(list1)
print(" the rows we want to print is", list1[1:3])
print(" in this we select the row and the columns and that number we have to print",list1[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 the rows we want to print is [[4 5 6]
 [7 8 9]]
 in this we select the row and the columns and that number we have to print [3 6 9]


In [12]:
list3= np.zeros((3,4,5))
print(list3)
list3.dtype

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


dtype('float64')

In [15]:
list4 =np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(list4[1:3,0])
print(list4[1:3,0:2])

[4 7]
[[4 5]
 [7 8]]
