<a href="https://colab.research.google.com/github/mukulSharma6230/mukul/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

now we have to change the variable so we can do 
by changing its index or if give an integer value it will automatically change to float type
Its will run it with intial stage
if we try to enter the string value of an alphabet it  will the error because it will not be able to change  and if be give the string of integer value in it and then it will be easy to change


In [5]:
x= np.ones(5)
x[2]=2
print(x)

[1. 1. 2. 1. 1.]


Create the 3d array

In [9]:
array_3d =np.zeros((3,4,5))

array_3d[0][1][3]=5
print(array_3d)
print(array_3d[0][1][3])

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 5. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
5.0


To get the shape we do

In [10]:
array_3d.shape

(3, 4, 5)