<a href="https://colab.research.google.com/github/mukulSharma6230/mukul/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

here we start learning the numpy
So it is the first one

In [1]:
import numpy as npm

now let us create a demo list so we want to create the array of numpy so we do
it will show us that it is a numpy array

In [3]:
demo =[10,20,30]

npm.array(demo)

array([10, 20, 30])

here we enter do thing it will make array of flot type 
If we want to gave us a int value we have to enter (5,int)
Than we can run it

In [4]:
npm.zeros(5)

array([0., 0., 0., 0., 0.])

here we see that on thing is  in array so it will change the data type into int and if  it found that that object are of alphabet than it will change the whole array into the string array

In [6]:
demo1 =[10,20,'30']
npm.array(demo1)

array(['10', '20', '30'], dtype='<U21')

In [7]:
demo2= [10,20,'xyz']
npm.array(demo2)

array(['10', '20', 'xyz'], dtype='<U21')

In [8]:
demo1[2]='xyz'
print(demo1)

[10, 20, 'xyz']


In [9]:
x  =npm.ones(5,int)
print(x)

[1 1 1 1 1]


In [11]:
x[2]= 5
print(x)

[1 1 5 1 1]


to find which type of array we have


In [12]:
y= npm.ones(5)
y.dtype

dtype('float64')